injury_keywords:
  - "abdomen"
  - "achilles"
  - "appendix"
  - "acl"
  - "ankle"
  - "back"
  - "biceps"
  - "break"
  - "broken bone"
  - "bruise"
  - "calf"
  - "chest"
  - "collarbone"
  - "concussion protocol"
  - "concussion"
  - "contusion"
  - "dislocation"
  - "elbow"
  - "fibula"
  - "finger"
  - "foot"
  - "forearm"
  - "fracture"
  - "fractured"
  - "fractured rib"
  - "fractured leg"
  - "groin"
  - "hammy"
  - "hamstring"
  - "hand"
  - "high ankle sprain"
  - "hip"
  - "inflammation"
  - "knee"
  - "lcl"
  - "lisfranc injury"
  - "lower body"
  - "lower-body"
  - "mcl"
  - "meniscus"
  - "neck"
  - "oblique"
  - "orbital fracture"
  - "pcl"
  - "pectoral"
  - "plantar fasciitis"
  - "quad"
  - "quadriceps"
  - "ribs"
  - "shin"
  - "shoulder"
  - "soreness"
  - "sports hernia"
  - "sprain"
  - "strain"
  - "surgery"
  - "tear"
  - "thumb"
  - "tightness"
  - "toe"
  - "tommy john surgery"
  - "torn achilles"
  - "torn acl"
  - "torn lcl"
  - "torn mcl"
  - "torn meniscus"
  - "torn pcl"
  - "triceps"
  - "turf toe"
  - "undisclosed"
  - "upper body"
  - "upper-body"
  - "wrist"

status_keywords:
  - "activated from injured reserve"
  - "activated from ir"
  - "active"
  - "added to injured reserve"
  - "added to the reserve/physically unable to perform list"
  - "added to ir"
  - "carted off"
  - "day-to-day"
  - "designated to return"
  - "DNP"
  - "did not return"
  - "doubtful"
  - "full participant"
  - "full"
  - "good to go"
  - "inactive"
  - "injured reserve"
  - "IR"
  - "limited participant"
  - "limited"
  - "listed as doubtful"
  - "listed as limited"
  - "listed as out"
  - "listed as questionable"
  - "miss the season"
  - "non-football injury list"
  - "on injured reserve"
  - "on the injured reserve"
  - "out for the season"
  - "out for the year"
  - "out"
  - "placed on injured reserve"
  - "placed on the injured reserve list"
  - "placed on ir"
  - "practiced"
  - "probable"
  - "questionable"
  - "undergone surgery"
  - "remainder of the season"
  - "removed from injured reserve"
  - "removed from ir"
  - "placed on injured reserve"
  - "placed on the reserve/physically unable to perform list"
  - "rest of the season"
  - "return from injured reserve"
  - "return from ir"
  - "reverted"
  - "ruled out"
  - "sat out"
  - "season ending"
  - "season-ending"
  - "week-to-week"
  - "will miss"
  - "will not practice"
  - "won't return this season"
  - "wont return"
  - "returning this season"
  - "reserve/pup list"
  - "pup list"
  - "designation to return"

org_blacklist:
  - "nfl"
  - "nfl network"
  - "espn"
  - "yahoo sports"
  - "nfl.com"
  - "espn.com"
  - "cbs sports"
  - "cbs"
  - "yahoo.com"
  - "kprc 2 houston"
  - "the athletic"

team_whitelist:
  - "philadelphia"

reporter_blacklist:
  - "reported by"
  - "reports"
  - "aaron wilson"
  - "adam schefter"
  - "ian rapoport"
  - "tom pelissero"
  - "mike garafolo"
  - "jay glazer"
  - "jim wyatt"
  - "ari horton"
  - "james boyd"
