injury_verbs:
- "aggravated"
- "broke"
- "bruised"
- "dislocated"
- "broken"
- "fractured"
- "sprained"
- "sustained"
- "tore"
- "torn"

injury_suffixes:
- "injury"
- "pain"
- "soreness"
- "issue"
- "tightness"
- "sprain"
- "strain"
- "tear"
- "fracture"
- "dislocation"
- "contusion"
- "inflammation"
- "surgery"

injury_keywords:
- "abdomen"
- "achilles"
- "appendix"
- "acl"
- "ankle"
- "back"
- "biceps"
- "break"
- "broken bone"
- "bruise"
- "calf"
- "chest"
- "collarbone"
- "concussion protocol"
- "concussion"
- "contusion"
- "dislocation"
- "elbow"
- "fibula"
- "finger"
- "foot"
- "forearm"
- "fracture"
- "groin"
- "hammy"
- "hamstring"
- "hand"
- "high ankle sprain"
- "hip"
- "inflammation"
- "knee"
- "knee injury"
- "lcl"
- "lisfranc injury"
- "lower body"
- "lower-body"
- "mcl"
- "meniscus"
- "neck"
- "oblique"
- "orbital fracture"
- "pcl"
- "pectoral"
- "plantar fasciitis"
- "quad"
- "quadriceps"
- "ribs"
- "shin"
- "shoulder"
- "soreness"
- "sports hernia"
- "sprain"
- "strain"
- "surgery"
- "tear"
- "thumb"
- "tightness"
- "toe"
- "tommy john surgery"
- "triceps"
- "turf toe"
- "undisclosed"
- "upper body"
- "upper-body"
- "wrist"

status_keywords:
- "active"
- "carted off"
- "day-to-day"
- "designated to return"
- "DNP"
- "sidelined"
- "did not return"
- "doubtful"
- "full participant"
- "good to go"
- "inactive"
- "injured reserve"
- "IR"
- "limited participant"
- "limited"
- "miss the season"
- "non-football injury list"
- "on injured reserve"
- "on the injured reserve"
- "out for the season"
- "out for the year"
- "ruled out"
- "practiced"
- "probable"
- "questionable"
- "remainder of the season"
- "rest of the season"
- "reverted"
- "sat out"
- "season ending"
- "season-ending"
- "week-to-week"
- "will miss"
- "will not practice"
- "won't return this season"
- "wont return"
- "returning this season"
- "reserve/pup list"
- "pup list"
- "designation to return"
- "season-ending"

status_prefixes:
- "activated from"
- "added to"
- "designated to"
- "downgraded to"
- "listed as"
- "placed on"
- "removed from"
- "return from"
- "taken off of"
- "suffered a"

org_blacklist:
- "nfl"
- "nfl network"
- "espn"
- "yahoo sports"
- "nfl.com"
- "espn.com"
- "cbs sports"
- "cbs"
- "yahoo.com"
- "kprc 2 houston"
- "the athletic"

team_whitelist:
- "philadelphia"

reporter_blacklist:
- "reported by"
- "reports"
- "aaron wilson"
- "adam schefter"
- "ian rapoport"
- "tom pelissero"
- "mike garafolo"
- "jay glazer"
- "jim wyatt"
- "ari horton"
- "james boyd"
